[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "prospero"
version = "0.1.0"
dependencies = [
    "evodiff>=1.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
]

[tool.setuptools.packages.find]
where = ["src"]
